"""
face_pulse/backend/app/models/measurement.py
=============================================
ORM model for the `measurements` table.

This is the central entity for the measurement lifecycle.
The `id` (UUID) is returned to the frontend as `measurement_id`.

Design constraints
------------------
* Only session-management columns are stored here.
* Raw camera frames, video blobs, rPPG signals, and ML tensors are
  intentionally excluded.  They will be handled by a separate storage
  layer (object store or specialist service) once contracts are finalised.
* No patient health values (heart_rate, spo2, etc.) are stored yet;
  these will be added in a later migration after the ML/signal-processing
  contracts are approved.

See docs/database.md for full design rationale.
"""

import enum
import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import Enum as SAEnum
from sqlalchemy import ForeignKey, TIMESTAMP, Index, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base

if TYPE_CHECKING:
    from app.models.user import User


# ---------------------------------------------------------------------------
# MeasurementStatus
# ---------------------------------------------------------------------------


class MeasurementStatus(str, enum.Enum):
    """
    Lifecycle states of a measurement session.

    Transitions (happy path):
        READY → MEASURING → PROCESSING → COMPLETED

    Error path:
        Any state → FAILED

    READY       The measurement record has been created and is waiting
                for the client to begin the camera capture.
    MEASURING   The client is actively capturing facial video.
    PROCESSING  Video capture is complete; the ML pipeline is running.
    COMPLETED   All signal values have been computed and stored.
    FAILED      An unrecoverable error occurred at any stage.
    """

    READY = "READY"
    MEASURING = "MEASURING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


# PostgreSQL ENUM type — shared between the model and the Alembic migration.
# Name must match the CREATE TYPE name in the migration exactly.
measurement_status_pg_enum = SAEnum(
    MeasurementStatus,
    name="measurement_status",      # PostgreSQL type name
    create_constraint=True,
    validate_strings=True,          # reject invalid strings at SQLAlchemy level
)


# ---------------------------------------------------------------------------
# Measurement model
# ---------------------------------------------------------------------------


class Measurement(Base):
    """
    ORM representation of the `measurements` table.

    Each row represents one measurement session initiated by a user.
    The `id` field is the canonical measurement_id exposed through the API.

    Columns
    -------
    id           Primary key UUID, auto-generated by the database.
    user_id      UUID of the user who initiated the measurement.
                 Indexed for fast per-user queries.
                 Foreign key to users.id.
    status       Current lifecycle state (see MeasurementStatus).
                 Defaults to READY on insert.
    started_at   When the measurement session began.
                 Set automatically by the database on insert.
    completed_at When the session reached COMPLETED or FAILED.
                 NULL until the session ends.
    created_at   Row creation timestamp.
                 Set automatically by the database on insert.

    Relationships
    -------------
    user         Many-to-one relationship to the owning User.
    """

    __tablename__ = "measurements"

    # ------------------------------------------------------------------
    # Primary key
    # ------------------------------------------------------------------
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,          # Python-side default (app layer)
        server_default=func.gen_random_uuid(),  # DB-side fallback
        comment="Canonical measurement identifier, exposed as measurement_id.",
    )

    # ------------------------------------------------------------------
    # User reference
    # ------------------------------------------------------------------
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id"),
        nullable=False,
        comment=(
            "UUID of the user who owns this measurement. "
            "Indexed for per-user queries. "
            "Foreign key referencing users.id."
        ),
    )

    user: Mapped["User"] = relationship(
        "User",
        back_populates="measurements",
    )

    # ------------------------------------------------------------------
    # Status
    # ------------------------------------------------------------------
    status: Mapped[MeasurementStatus] = mapped_column(
        measurement_status_pg_enum,
        nullable=False,
        default=MeasurementStatus.READY,
        server_default=MeasurementStatus.READY.value,
        comment="Current lifecycle state of the measurement session.",
    )

    # ------------------------------------------------------------------
    # Timestamps — always timezone-aware (TIMESTAMPTZ in PostgreSQL)
    # ------------------------------------------------------------------
    started_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="When the measurement session began (set by DB on insert).",
    )

    completed_at: Mapped[datetime | None] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=True,
        default=None,
        comment=(
            "When the session reached COMPLETED or FAILED. "
            "NULL until the session ends."
        ),
    )

    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="Row creation timestamp (set by DB on insert).",
    )

    # ------------------------------------------------------------------
    # Table-level constraints and indexes
    # ------------------------------------------------------------------
    __table_args__ = (
        Index("ix_measurements_user_id", "user_id"),
    )

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------
    def __repr__(self) -> str:  # pragma: no cover
        return (
            f"<Measurement id={self.id} user_id={self.user_id} "
            f"status={self.status.value}>"
        )
