"""
face_pulse/backend/app/models/user.py
======================================
ORM model for the `users` table.

Represents a user account in the Face Pulse healthcare application.
Establishes a 1:N relationship with the Measurement model.
"""

import enum
import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import Enum as SAEnum
from sqlalchemy import Boolean, TIMESTAMP, String, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base

if TYPE_CHECKING:
    from app.models.measurement import Measurement
    from app.models.user_guardian import UserGuardian


# ---------------------------------------------------------------------------
# UserRole ENUM
# ---------------------------------------------------------------------------


class UserRole(str, enum.Enum):
    """
    User roles in the application.

    Currently, all accounts are assigned USER role.
    Additional roles (e.g. DOCTOR, ADMIN) are deferred to future milestones.
    """

    USER = "USER"


# PostgreSQL ENUM type for user_role
user_role_pg_enum = SAEnum(
    UserRole,
    name="user_role",
    create_constraint=True,
    validate_strings=True,
)


# ---------------------------------------------------------------------------
# User model
# ---------------------------------------------------------------------------


class User(Base):
    """
    ORM representation of the `users` table.

    Columns
    -------
    id            Primary key UUID, auto-generated by the database.
    full_name     Full name of the user (VARCHAR(100), required).
    email         User email address (unique, indexed, VARCHAR(255), required).
    password_hash Hashed password string (required, plaintext forbidden).
    role          Role enum (user_role ENUM, default: USER).
    is_active     Active account flag (Boolean, default: True).
    created_at    Account creation timestamp (TIMESTAMPTZ, auto now()).
    updated_at    Account last update timestamp (TIMESTAMPTZ, auto now()).

    Relationships
    -------------
    measurements           1:N relationship to Measurement rows owned by this user.
    guardian_relationships 1:N relationship to UserGuardian rows where this user is the data owner.
    owned_guardians        1:N relationship to UserGuardian rows where this user is the guardian recipient.
    """

    __tablename__ = "users"

    # ------------------------------------------------------------------
    # Primary key
    # ------------------------------------------------------------------
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.gen_random_uuid(),
        comment="Primary key UUID for the user account (independent from measurement.id).",
    )

    # ------------------------------------------------------------------
    # Profile & Credentials
    # ------------------------------------------------------------------
    full_name: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        comment="Full name of the user.",
    )

    email: Mapped[str] = mapped_column(
        String(255),
        unique=True,
        nullable=False,
        index=True,
        comment="Unique user email address.",
    )

    password_hash: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        comment="Hashed password string (never store plaintext).",
    )

    role: Mapped[UserRole] = mapped_column(
        user_role_pg_enum,
        nullable=False,
        default=UserRole.USER,
        server_default=UserRole.USER.value,
        comment="User role (PostgreSQL ENUM 'user_role', defaults to USER).",
    )

    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        server_default=text("true"),
        comment="Boolean flag indicating whether the user account is active.",
    )

    # ------------------------------------------------------------------
    # Timestamps
    # ------------------------------------------------------------------
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="Account creation timestamp (set by DB on insert).",
    )

    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        comment="Account update timestamp.",
    )

    # ------------------------------------------------------------------
    # Relationships
    # ------------------------------------------------------------------
    measurements: Mapped[list["Measurement"]] = relationship(
        "Measurement",
        back_populates="user",
    )

    # Relationships where this user is the data owner (user_id)
    guardian_relationships: Mapped[list["UserGuardian"]] = relationship(
        "UserGuardian",
        foreign_keys="[UserGuardian.user_id]",
        back_populates="user",
    )

    # Relationships where this user is the guardian recipient (guardian_user_id)
    owned_guardians: Mapped[list["UserGuardian"]] = relationship(
        "UserGuardian",
        foreign_keys="[UserGuardian.guardian_user_id]",
        back_populates="guardian_user",
    )

    def __repr__(self) -> str:  # pragma: no cover
        return f"<User id={self.id} email={self.email!r} role={self.role.value}>"
