"""
face_pulse/backend/app/models/user_guardian.py
===============================================
ORM model for the `user_guardians` table.

Represents a guardian relationship between two Face Pulse user accounts.

Key Concept
-----------
Both the data owner (user_id) and the guardian recipient (guardian_user_id)
are standard user accounts in the `users` table with role='USER'.
There is NO separate 'GUARDIAN' role.

Identifer Rule
--------------
user_guardians.id is an independent UUID.
It is distinct from users.id and measurements.id.
"""

import enum
import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import Enum as SAEnum
from sqlalchemy import Boolean, CheckConstraint, ForeignKey, TIMESTAMP, UniqueConstraint, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base

if TYPE_CHECKING:
    from app.models.user import User


# ---------------------------------------------------------------------------
# GuardianRelationshipStatus ENUM
# ---------------------------------------------------------------------------


class GuardianRelationshipStatus(str, enum.Enum):
    """
    Lifecycle status of a guardian relationship invitation.

    PENDING   - Invitation sent by data owner, awaiting recipient response.
    ACCEPTED  - Recipient accepted the relationship; sharing permissions active.
    REJECTED  - Recipient rejected the invitation.
    REVOKED   - Relationship was accepted, but later revoked by owner or guardian.
    """

    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    REVOKED = "REVOKED"


# PostgreSQL ENUM type for guardian_relationship_status
guardian_relationship_status_pg_enum = SAEnum(
    GuardianRelationshipStatus,
    name="guardian_relationship_status",
    create_constraint=True,
    validate_strings=True,
)


# ---------------------------------------------------------------------------
# UserGuardian Model
# ---------------------------------------------------------------------------


class UserGuardian(Base):
    """
    ORM representation of the `user_guardians` table.

    Columns
    -------
    id               Primary key UUID, auto-generated by DB.
    user_id          UUID of the data owner (users.id).
    guardian_user_id UUID of the guardian account (users.id).
    status           Relationship status (PENDING, ACCEPTED, REJECTED, REVOKED).
    share_results    Boolean flag: permission to view completed measurement results.
    share_trends     Boolean flag: permission to view historical trends.
    share_alerts     Boolean flag: permission to receive measurement alerts.
    created_at       TIMESTAMPTZ, auto-generated.
    updated_at       TIMESTAMPTZ, auto-generated with onupdate.

    Constraints
    -----------
    * Foreign key user_id -> users.id (no CASCADE delete).
    * Foreign key guardian_user_id -> users.id (no CASCADE delete).
    * Check constraint user_id <> guardian_user_id (prevents self-guardian).
    * Unique constraint (user_id, guardian_user_id) (prevents duplicate pairs).
    """

    __tablename__ = "user_guardians"

    # ------------------------------------------------------------------
    # Primary key
    # ------------------------------------------------------------------
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.gen_random_uuid(),
        comment="Primary key UUID for the guardian relationship.",
    )

    # ------------------------------------------------------------------
    # Foreign Keys & References
    # ------------------------------------------------------------------
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id"),
        nullable=False,
        index=True,
        comment="UUID of the user account who owns the measurement data.",
    )

    guardian_user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id"),
        nullable=False,
        index=True,
        comment="UUID of the user account receiving guardian access.",
    )

    # ------------------------------------------------------------------
    # Relationship Status & Permissions
    # ------------------------------------------------------------------
    status: Mapped[GuardianRelationshipStatus] = mapped_column(
        guardian_relationship_status_pg_enum,
        nullable=False,
        default=GuardianRelationshipStatus.PENDING,
        server_default=GuardianRelationshipStatus.PENDING.value,
        comment="Current status of the guardian relationship.",
    )

    share_results: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        server_default=text("false"),
        comment="Permission flag for viewing completed measurement results.",
    )

    share_trends: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        server_default=text("false"),
        comment="Permission flag for viewing historical measurement trends.",
    )

    share_alerts: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        server_default=text("false"),
        comment="Permission flag for receiving measurement alerts.",
    )

    # ------------------------------------------------------------------
    # Timestamps
    # ------------------------------------------------------------------
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="Relationship creation timestamp.",
    )

    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        comment="Relationship update timestamp.",
    )

    # ------------------------------------------------------------------
    # Relationships
    # ------------------------------------------------------------------
    user: Mapped["User"] = relationship(
        "User",
        foreign_keys=[user_id],
        back_populates="guardian_relationships",
    )

    guardian_user: Mapped["User"] = relationship(
        "User",
        foreign_keys=[guardian_user_id],
        back_populates="owned_guardians",
    )

    # ------------------------------------------------------------------
    # Table-level Constraints
    # ------------------------------------------------------------------
    __table_args__ = (
        CheckConstraint(
            "user_id <> guardian_user_id",
            name="ck_user_guardians_prevent_self_guardian",
        ),
        UniqueConstraint(
            "user_id",
            "guardian_user_id",
            name="uq_user_guardians_user_guardian",
        ),
    )

    def __repr__(self) -> str:  # pragma: no cover
        return (
            f"<UserGuardian id={self.id} user_id={self.user_id} "
            f"guardian_user_id={self.guardian_user_id} status={self.status.value}>"
        )
