"""
face_pulse/backend/app/models/user_profile.py
================================================
ORM model for the `user_profiles` table.

Represents the health and demographic profile for a Face Pulse user.

Design Principles
-----------------
1. One-to-one relationship with `users` (user_id is UNIQUE).
2. Derived metrics (`age` and `bmi`) are implemented as Python properties
   and are NOT stored as permanent database columns to prevent stale data.
3. Health/demographic data is kept in this dedicated table rather than
   polluting the core `users` authentication table.
4. Primary key `id` is an independent UUID.
"""

import enum
import uuid
from datetime import date, datetime
from decimal import Decimal
from typing import TYPE_CHECKING

from sqlalchemy import Enum as SAEnum
from sqlalchemy import CheckConstraint, Date, ForeignKey, Numeric, TIMESTAMP, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base

if TYPE_CHECKING:
    from app.models.user import User


# ---------------------------------------------------------------------------
# Gender ENUM
# ---------------------------------------------------------------------------


class Gender(str, enum.Enum):
    """
    Gender representation for health and physiological context.
    """

    MALE = "MALE"
    FEMALE = "FEMALE"
    OTHER = "OTHER"
    PREFER_NOT_TO_SAY = "PREFER_NOT_TO_SAY"


gender_pg_enum = SAEnum(
    Gender,
    name="gender_enum",
    create_constraint=True,
    validate_strings=True,
)


# ---------------------------------------------------------------------------
# BloodGroup ENUM
# ---------------------------------------------------------------------------


class BloodGroup(str, enum.Enum):
    """
    Standard ABO/Rh blood group categories.
    """

    A_POSITIVE = "A+"
    A_NEGATIVE = "A-"
    B_POSITIVE = "B+"
    B_NEGATIVE = "B-"
    AB_POSITIVE = "AB+"
    AB_NEGATIVE = "AB-"
    O_POSITIVE = "O+"
    O_NEGATIVE = "O-"


blood_group_pg_enum = SAEnum(
    BloodGroup,
    name="blood_group_enum",
    create_constraint=True,
    validate_strings=True,
)


# ---------------------------------------------------------------------------
# UserProfile Model
# ---------------------------------------------------------------------------


class UserProfile(Base):
    """
    ORM representation of the `user_profiles` table.

    Columns
    -------
    id            Primary key UUID, auto-generated by the database.
    user_id       UUID of the owning user (ForeignKey to users.id, UNIQUE, NOT NULL).
    date_of_birth Date of birth (DATE, required).
    gender        Gender enum (gender_enum, required).
    height_cm     Height in centimeters (NUMERIC(5,2), > 0, required).
    weight_kg     Weight in kilograms (NUMERIC(5,2), > 0, required).
    blood_group   Blood group enum (blood_group_enum, required).
    created_at    TIMESTAMPTZ, auto now().
    updated_at    TIMESTAMPTZ, auto now(), onupdate now().

    Derived Properties (Not Stored in DB)
    --------------------------------------
    age           Calculated dynamically from date_of_birth.
    bmi           Calculated dynamically from weight_kg and height_cm (weight / height_m^2).
    """

    __tablename__ = "user_profiles"

    # ------------------------------------------------------------------
    # Primary key
    # ------------------------------------------------------------------
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.gen_random_uuid(),
        comment="Primary key UUID for the user health profile.",
    )

    # ------------------------------------------------------------------
    # User reference (1:1 relationship via UNIQUE constraint)
    # ------------------------------------------------------------------
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id"),
        unique=True,
        nullable=False,
        index=True,
        comment="UUID of the associated user (enforces 1:1 relationship).",
    )

    # ------------------------------------------------------------------
    # Demographic and Health Attributes
    # ------------------------------------------------------------------
    date_of_birth: Mapped[date] = mapped_column(
        Date,
        nullable=False,
        comment="User date of birth (used to calculate derived age).",
    )

    gender: Mapped[Gender] = mapped_column(
        gender_pg_enum,
        nullable=False,
        comment="Gender representation for health context.",
    )

    height_cm: Mapped[Decimal] = mapped_column(
        Numeric(5, 2),
        nullable=False,
        comment="Height in centimeters (must be > 0).",
    )

    weight_kg: Mapped[Decimal] = mapped_column(
        Numeric(5, 2),
        nullable=False,
        comment="Weight in kilograms (must be > 0).",
    )

    blood_group: Mapped[BloodGroup] = mapped_column(
        blood_group_pg_enum,
        nullable=False,
        comment="ABO/Rh blood group category.",
    )

    # ------------------------------------------------------------------
    # Timestamps
    # ------------------------------------------------------------------
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="Profile creation timestamp.",
    )

    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        comment="Profile update timestamp.",
    )

    # ------------------------------------------------------------------
    # Relationship
    # ------------------------------------------------------------------
    user: Mapped["User"] = relationship(
        "User",
        back_populates="profile",
    )

    # ------------------------------------------------------------------
    # Table Constraints
    # ------------------------------------------------------------------
    __table_args__ = (
        CheckConstraint(
            "height_cm > 0",
            name="ck_user_profiles_positive_height",
        ),
        CheckConstraint(
            "weight_kg > 0",
            name="ck_user_profiles_positive_weight",
        ),
    )

    # ------------------------------------------------------------------
    # Derived Properties (Calculated dynamically, not stored in DB)
    # ------------------------------------------------------------------
    @property
    def age(self) -> int:
        """
        Calculate current age in full years from date_of_birth.
        Derived at runtime — NOT stored in the database.
        """
        today = date.today()
        dob = self.date_of_birth
        return (
            today.year
            - dob.year
            - ((today.month, today.day) < (dob.month, dob.day))
        )

    @property
    def bmi(self) -> float:
        """
        Calculate Body Mass Index (BMI): weight_kg / (height_m ^ 2).
        Derived at runtime — NOT stored in the database.
        """
        height_m = float(self.height_cm) / 100.0
        return round(float(self.weight_kg) / (height_m**2), 2)

    def __repr__(self) -> str:  # pragma: no cover
        return (
            f"<UserProfile id={self.id} user_id={self.user_id} "
            f"gender={self.gender.value} blood_group={self.blood_group.value}>"
        )
