const List<String> wellnessQuotes = [
  "Your body hears everything your mind says. Keep it positive.",
  "Every heartbeat is a universe of potential. Listen to your rhythm.",
  "Health is not about the weight you lose, but the life you gain.",
  "The quietest moments often yield the clearest insights about your health.",
  "Small daily habits form the foundation of a long and vibrant life.",
  "Your pulse is the song of your life force. Keep it steady and strong.",
  "Rest is not laziness; it is an essential phase of active recovery.",
  "Invest in your health today. It pays the highest interest tomorrow.",
  "Nourish your body, calm your mind, and let your spirit soar.",
  "Consistency beats intensity. Micro-actions lead to macro results.",
  "True wellness is a harmonious balance of body, mind, and soul.",
  "A healthy heart is a fountain of energy and joy. Protect it.",
  "Let your breath be your anchor in times of chaos and stress.",
  "Every step forward is a step closer to your healthiest self.",
  "Listen to your body's whispers before they turn into screams.",
  "Sleep is the golden chain that ties health and our bodies together.",
  "Your health is an investment, not an expense. Prioritize it.",
  "Take care of your body. It is the only place you have to live in.",
  "A calm mind brings inner strength and self-confidence.",
  "Choose wellness over convenience. Your future self will thank you.",
  "Hydrate, meditate, and appreciate. Simple acts of daily self-care.",
  "Your heart pumps life through you; give it the rest and care it deserves.",
  "Wellness is a journey, not a destination. Celebrate each small win.",
  "Movement is medicine. Find a way to keep your body active today.",
  "Breathing in, I calm my body. Breathing out, I smile.",
  "Be gentle with yourself. You are doing the best you can.",
  "Good health is the greatest wealth you can ever possess.",
  "Every day is another chance to build a stronger, healthier version of you.",
  "Self-care is how you take your power back.",
  "Protect your energy, clear your mind, and listen to your pulse.",
  "A vibrant life begins with a mindful heart.",
  "Your biometrics are the story of your lifestyle. Write a good one.",
  "Give yourself permission to slow down and breathe deeply.",
  "The greatest medicine of all is to teach people how not to need it.",
  "An ounce of prevention is worth a pound of cure.",
  "Wellness is the natural state of an aligned body and mind.",
  "Eat to nourish, run to empower, rest to recover.",
  "Your heart rate reflects your response to the world. Seek peace.",
  "A resilient heart adapts to life's shifts. Nurture your HRV.",
  "Track your progress, trust the process, and stay patient.",
  "May your heart beat steady and your mind remain serene.",
  "Health is a relationship between you and your body.",
  "Calm your nervous system. Box breathing is a superpower.",
  "The key to wellness is listening to the subtle signals of your body.",
  "Every deep breath increases your vital energy and clears your mind.",
  "Prioritize sleep. It is the ultimate metric of recovery.",
  "Step outside and let nature reset your circadian rhythm.",
  "Your health is your primary wealth. Guard it diligently.",
  "Choose food that makes your cells sing with vitality.",
  "A peaceful heart is a healthy heart. Release what you cannot control.",
  "Laughter is a wonderful therapy. Keep your heart light.",
  "Be proactive, not reactive, when it comes to your well-being.",
  "Your heart is a masterpiece of biological engineering. Honor it.",
  "Hydration is key. Drink water to fuel your daily energy.",
  "HRV is a window into your nervous system balance. Keep it high.",
  "A single mindful breath can break the cycle of daily stress.",
  "Health is the capacity for love, work, and play.",
  "Stretching keeps your muscles flexible, strong, and healthy.",
  "Your body is a temple, but only if you treat it as one.",
  "A healthy heart is a happy heart. Fill it with gratitude.",
  "Take a walk. Fresh air is a natural mood booster.",
  "Rest your eyes and quiet your mind for five minutes today.",
  "Your breathing rate is a remote control for your brain. Slow it down.",
  "The body heals with play, the mind heals with laughter.",
  "Focus on progress, not perfection. Every metric counts.",
  "A calm heart pumps blood with ease. Practice mindfulness.",
  "Wellness is about adding years to your life and life to your years.",
  "Daily meditation is a sanctuary for your heart and soul.",
  "Nurture your relationships. Connection is vital to longevity.",
  "Your biometrics are unique. Focus on your personal baseline.",
  "A good night's sleep is the best recovery tool available.",
  "Wellness is active exploration. Keep seeking balance.",
  "Make time for hobbies that bring you pure, stress-free joy.",
  "Your pulse tells a story of adaptation and strength.",
  "A healthy lifestyle is a collection of small daily victories.",
  "Live in the present moment. Your heart will thank you.",
  "Hydrate your cells, activate your muscles, and clear your mind.",
  "Protect your cardiovascular health with consistent, daily steps.",
  "The foundation of success is good physical and mental health.",
  "Rest is the cornerstone of progress. Never underestimate it.",
  "Your heart works hard for you. Give it moments of stillness.",
  "Breathe in strength, breathe out tension.",
  "A resilient mind creates a resilient cardiovascular system.",
  "Cherish your health while you have it. It is a gift.",
  "Wellness is self-respect in action.",
  "Track your daily metrics to understand your body's language.",
  "Eat whole foods, walk daily, and worry less.",
  "Your pulse is the beat of life. Keep dancing to its rhythm.",
  "Health is not merely the absence of disease, but total vitality.",
  "Unplug from screens and connect with your inner baseline.",
  "A steady breath signals safety to your nervous system.",
  "Invest time in daily activity. Movement is youthfulness.",
  "Celebrate your body's incredible ability to adapt and heal.",
  "A grateful heart has a lower resting pulse rate.",
  "Listen to your heart rate variability. It knows when you need rest.",
  "Wellness is the dynamic state of positive health.",
  "Simple habits lead to a powerful life. Stay consistent.",
  "Your health checks are acts of self-love and awareness.",
  "Keep your heart strong, your mind clear, and your body moving.",
  "The journey of a thousand miles begins with a single deep breath."
];
