"""Create measurements table with measurement_status enum.

Revision ID: 0001
Revises: (initial migration)
Create Date: 2026-08-14

Summary
-------
Creates:
  * measurement_status  — PostgreSQL ENUM type
  * measurements        — Central measurement-session table
  * ix_measurements_user_id — Index on user_id for fast per-user queries

Design notes
------------
* UUID primary key (gen_random_uuid()) — portable, collision-resistant,
  suitable for direct exposure as measurement_id in the API.
* All timestamps are TIMESTAMPTZ (timezone-aware) to avoid timezone
  ambiguity in a healthcare application.
* started_at and created_at both default to now() (server-side) so
  they are set correctly regardless of the app-layer clock.
* completed_at is nullable — it is NULL until the session ends.
* status defaults to 'READY' (server-side) so newly created rows
  always have a valid state.
* No FK on user_id yet — the users table is defined on a separate branch.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# ---------------------------------------------------------------------------
# Revision identifiers
# ---------------------------------------------------------------------------
revision: str = "0001"
down_revision: Union[str, None] = None   # first migration — no parent
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ---------------------------------------------------------------------------
# Enum definition — declared here so both upgrade() and downgrade() can use it
# ---------------------------------------------------------------------------
measurement_status_enum = postgresql.ENUM(
    "READY",
    "MEASURING",
    "PROCESSING",
    "COMPLETED",
    "FAILED",
    name="measurement_status",
    create_type=False,   # we manage creation/deletion explicitly below
)


# ---------------------------------------------------------------------------
# upgrade
# ---------------------------------------------------------------------------
def upgrade() -> None:
    # 1. Create the PostgreSQL ENUM type first (table depends on it)
    measurement_status_enum.create(op.get_bind(), checkfirst=True)

    # 2. Create the measurements table
    op.create_table(
        "measurements",

        # Primary key — UUID auto-generated by PostgreSQL
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Canonical measurement identifier, exposed as measurement_id.",
        ),

        # User reference — UUID, NOT NULL, indexed (no FK yet)
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
            comment=(
                "UUID of the user who owns this measurement. "
                "No FK constraint until the users table is formally defined."
            ),
        ),

        # Measurement lifecycle status — ENUM, NOT NULL, default READY
        sa.Column(
            "status",
            postgresql.ENUM(
                "READY", "MEASURING", "PROCESSING", "COMPLETED", "FAILED",
                name="measurement_status",
                create_type=False,
            ),
            nullable=False,
            server_default="READY",
            comment="Current lifecycle state of the measurement session.",
        ),

        # Timestamps — TIMESTAMPTZ, server-side defaults
        sa.Column(
            "started_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
            comment="When the measurement session began (set by DB on insert).",
        ),
        sa.Column(
            "completed_at",
            sa.TIMESTAMP(timezone=True),
            nullable=True,
            comment=(
                "When the session reached COMPLETED or FAILED. "
                "NULL until the session ends."
            ),
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
            comment="Row creation timestamp (set by DB on insert).",
        ),
    )

    # 3. Create index on user_id for fast per-user lookups
    op.create_index(
        "ix_measurements_user_id",
        "measurements",
        ["user_id"],
        unique=False,
    )


# ---------------------------------------------------------------------------
# downgrade
# ---------------------------------------------------------------------------
def downgrade() -> None:
    # 1. Drop index first
    op.drop_index("ix_measurements_user_id", table_name="measurements")

    # 2. Drop the table (this also drops column-level enum usage)
    op.drop_table("measurements")

    # 3. Drop the ENUM type (must come after table is gone)
    measurement_status_enum.drop(op.get_bind(), checkfirst=True)
